name: ARM64 Mainline autobuilder

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Build kernel
        run: |
          cd $GITHUB_WORKSPACE
          echo 'deb-src http://azure.archive.ubuntu.com/ubuntu/ noble main universe restricted' | sudo tee -a /etc/apt/sources.list
          echo 'deb-src http://azure.archive.ubuntu.com/ubuntu/ noble-updates main universe restricted' | sudo tee -a /etc/apt/sources.list
          echo 'deb-src http://azure.archive.ubuntu.com/ubuntu/ noble-security main universe restricted' | sudo tee -a /etc/apt/sources.list
          echo 'deb-src http://azure.archive.ubuntu.com/ubuntu/ noble-backports main universe restricted' | sudo tee -a /etc/apt/sources.list

          sudo apt update
          sudo apt build-dep linux -y
          sudo apt install flex bison lld llvm clang libarchive-tools -y

          ./build arm64 mainline
          ./build arm64 jhovold-x1e
      - uses: actions/upload-artifact@v4.4.3
        name: Upload artifacts  
        with:
          name: cadmium-update images
          path: dist/*
